# -*- coding: utf-8 -*-
"""shows_analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HDnxKoVfGYVxVnkDeQh9huDd15kAul1V

# 📺 Shows Dataset — Data Understanding Layer
**Covers:** Basic statistical analysis · Keyword frequency analysis · Dataset exploration · Visualizations

## 0. Setup & Imports
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.ticker as mticker
import seaborn as sns
from collections import Counter
import ast
import warnings
warnings.filterwarnings('ignore')

# ── Style ──────────────────────────────────────────────────────────────────
sns.set_theme(style='whitegrid', palette='muted', font_scale=1.1)
plt.rcParams['figure.dpi'] = 120
plt.rcParams['axes.spines.top']   = False
plt.rcParams['axes.spines.right'] = False

print('✅ Libraries ready')

"""## 1. Load Data"""

# ── Upload your file when running in Colab ─────────────────────────────────
# from google.colab import files
# uploaded = files.upload()   # choose shows_processed.csv
# df = pd.read_csv(list(uploaded.keys())[0])

# ── OR load directly if already in the runtime ────────────────────────────
df = pd.read_csv('shows_processed.csv')

# Parse token columns (stored as stringified lists)
for col in ['showname_tokens', 'slug_tokens', 'all_tokens']:
    df[col] = df[col].apply(lambda x: ast.literal_eval(x) if isinstance(x, str) else [])

print(f'Shape: {df.shape[0]:,} rows × {df.shape[1]} columns')
df.head()

"""---
## 2. Dataset Exploration
"""

# ── Column types & memory ──────────────────────────────────────────────────
print('=== Column Info ===')
df.info()
print()

# ── Missing values ─────────────────────────────────────────────────────────
missing = df.isnull().sum()
missing_pct = (missing / len(df) * 100).round(2)
miss_df = pd.DataFrame({'missing_count': missing, 'missing_%': missing_pct})
miss_df = miss_df[miss_df['missing_count'] > 0]
print('=== Missing Values ===')
print(miss_df if not miss_df.empty else 'No missing values')
print()

# ── Unique counts ──────────────────────────────────────────────────────────
print('=== Unique Values per Column ===')
# Exclude list columns which are unhashable for nunique()
print(df.drop(columns=['showname_tokens', 'slug_tokens', 'all_tokens']).nunique().to_string())

# ── Sample rows ────────────────────────────────────────────────────────────
print('Random sample of 5 shows:')
df[['showname', 'seasons', 'episodes', 'rating', 'token_count']].sample(5, random_state=42)

"""---
## 3. Basic Statistical Analysis
"""

# ── Descriptive stats for numeric columns ─────────────────────────────────
numeric_cols = ['seasons', 'episodes', 'rating', 'token_count']
stats = df[numeric_cols].describe().T
stats['median']  = df[numeric_cols].median()
stats['skewness'] = df[numeric_cols].skew().round(3)
stats['kurtosis'] = df[numeric_cols].kurt().round(3)
print('=== Extended Descriptive Statistics ===')
stats.round(3)

# ── Season distribution ────────────────────────────────────────────────────
print('Seasons value counts (top 10):')
print(df['seasons'].value_counts().head(10).to_string())
print()

# ── Rating brackets ────────────────────────────────────────────────────────
bins   = [0, 5, 6, 7, 7.5, 8, 8.5, 9, 10]
labels = ['<5','5-6','6-7','7-7.5','7.5-8','8-8.5','8.5-9','9+']
df['rating_bracket'] = pd.cut(df['rating'], bins=bins, labels=labels)
print('Rating bracket distribution:')
print(df['rating_bracket'].value_counts().sort_index().to_string())

# ── Correlation matrix ────────────────────────────────────────────────────
print('=== Correlation Matrix (numeric columns) ===')
df[numeric_cols].corr().round(3)

"""---
## 4. Keyword Frequency Analysis
"""

# ── All tokens frequency ──────────────────────────────────────────────────
all_words = [tok for tokens in df['all_tokens'] for tok in tokens]
freq = Counter(all_words)
freq_df = pd.DataFrame(freq.most_common(30), columns=['keyword', 'count'])

print(f'Total unique keywords: {len(freq):,}')
print(f'Total keyword occurrences: {len(all_words):,}')
print()
print('Top 30 keywords:')
freq_df

# ── Token count distribution per show ─────────────────────────────────────
print('Token count distribution per show:')
print(df['token_count'].value_counts().sort_index().to_string())
print()

# ── Shows with zero tokens (empty slug/name) ──────────────────────────────
zero_token = df[df['token_count'] == 0]
print(f'Shows with 0 tokens: {len(zero_token)} ({len(zero_token)/len(df)*100:.1f}%)')
if not zero_token.empty:
    print(zero_token[['showname', 'slug']].head(5).to_string())

# ── Average rating by most-common keyword ─────────────────────────────────
top_keywords = [w for w, _ in freq.most_common(15)]

kw_stats = []
for kw in top_keywords:
    mask = df['all_tokens'].apply(lambda toks: kw in toks)
    sub = df[mask]
    kw_stats.append({
        'keyword': kw,
        'show_count': len(sub),
        'avg_rating': sub['rating'].mean().round(3),
        'avg_episodes': sub['episodes'].mean().round(1)
    })

kw_stats_df = pd.DataFrame(kw_stats).sort_values('show_count', ascending=False)
print('Top keywords — show count & avg rating:')
kw_stats_df

"""---
## 5. Visualizations
"""

# ── Fig 1: Rating Distribution ─────────────────────────────────────────────
fig, axes = plt.subplots(1, 2, figsize=(14, 5))

# Histogram
axes[0].hist(df['rating'], bins=25, color='steelblue', edgecolor='white', alpha=0.85)
axes[0].axvline(df['rating'].mean(),   color='red',    linestyle='--', lw=1.5, label=f"Mean: {df['rating'].mean():.2f}")
axes[0].axvline(df['rating'].median(), color='orange', linestyle='-',  lw=1.5, label=f"Median: {df['rating'].median():.2f}")
axes[0].set_title('Rating Distribution', fontweight='bold')
axes[0].set_xlabel('Rating'); axes[0].set_ylabel('Count')
axes[0].legend()

# Box plot by bracket
bracket_order = [str(l) for l in labels if str(l) in df['rating_bracket'].dropna().astype(str).unique()]
df_valid = df.dropna(subset=['rating_bracket'])
df_valid.boxplot(column='rating', by='rating_bracket', ax=axes[1],
                 order=bracket_order, notch=False,
                 boxprops=dict(color='steelblue'),
                 medianprops=dict(color='red', lw=2))
axes[1].set_title('Rating Spread by Bracket', fontweight='bold')
axes[1].set_xlabel('Rating Bracket'); axes[1].set_ylabel('Rating')
fig.suptitle('')

plt.tight_layout()
plt.savefig('fig1_rating_distribution.png', bbox_inches='tight')
plt.show()

# ── Fig 2: Seasons & Episodes ──────────────────────────────────────────────
fig, axes = plt.subplots(1, 2, figsize=(14, 5))

# Seasons bar
season_counts = df['seasons'].value_counts().sort_index()
axes[0].bar(season_counts.index, season_counts.values,
            color=sns.color_palette('Blues_d', len(season_counts)), edgecolor='white')
axes[0].set_title('Number of Shows by Season Count', fontweight='bold')
axes[0].set_xlabel('Seasons'); axes[0].set_ylabel('Number of Shows')
axes[0].xaxis.set_major_locator(mticker.MaxNLocator(integer=True))

# Episodes (log scale for skewed distribution)
axes[1].hist(df['episodes'], bins=30, color='mediumseagreen', edgecolor='white', alpha=0.85)
axes[1].set_title('Episode Count Distribution', fontweight='bold')
axes[1].set_xlabel('Episodes'); axes[1].set_ylabel('Count')
axes[1].axvline(df['episodes'].median(), color='red', linestyle='--', lw=1.5,
                label=f"Median: {df['episodes'].median():.0f}")
axes[1].legend()

plt.tight_layout()
plt.savefig('fig2_seasons_episodes.png', bbox_inches='tight')
plt.show()

# ── Fig 3: Top 20 Keywords Bar Chart ──────────────────────────────────────
top20 = freq_df.head(20).sort_values('count')

fig, ax = plt.subplots(figsize=(10, 8))
colors = sns.color_palette('RdYlGn', len(top20))
bars = ax.barh(top20['keyword'], top20['count'], color=colors, edgecolor='white')
for bar, val in zip(bars, top20['count']):
    ax.text(bar.get_width() + 0.3, bar.get_y() + bar.get_height()/2,
            str(val), va='center', fontsize=9)
ax.set_title('Top 20 Most Frequent Keywords in Show Names', fontweight='bold', fontsize=13)
ax.set_xlabel('Frequency')
ax.set_xlim(0, top20['count'].max() * 1.12)

plt.tight_layout()
plt.savefig('fig3_keyword_frequency.png', bbox_inches='tight')
plt.show()

# ── Fig 4: Scatter — Episodes vs Rating (coloured by Seasons) ─────────────
df_scatter = df.dropna(subset=['seasons'])

fig, ax = plt.subplots(figsize=(10, 6))
scatter = ax.scatter(
    df_scatter['episodes'], df_scatter['rating'],
    c=df_scatter['seasons'], cmap='viridis',
    alpha=0.7, s=60, edgecolors='white', linewidths=0.4
)
plt.colorbar(scatter, ax=ax, label='Seasons')
ax.set_title('Episodes vs Rating (colour = Season count)', fontweight='bold')
ax.set_xlabel('Number of Episodes')
ax.set_ylabel('Rating')

# Trend line
m, b = np.polyfit(df_scatter['episodes'], df_scatter['rating'], 1)
x_line = np.linspace(df_scatter['episodes'].min(), df_scatter['episodes'].max(), 100)
ax.plot(x_line, m*x_line + b, color='red', linestyle='--', lw=1.5, label='Trend')
ax.legend()

plt.tight_layout()
plt.savefig('fig4_episodes_vs_rating.png', bbox_inches='tight')
plt.show()

# ── Fig 5: Correlation Heatmap ─────────────────────────────────────────────
fig, ax = plt.subplots(figsize=(7, 5))
corr = df[numeric_cols].corr()
mask = np.triu(np.ones_like(corr, dtype=bool))
sns.heatmap(corr, annot=True, fmt='.2f', cmap='coolwarm',
            mask=mask, linewidths=0.5, ax=ax,
            vmin=-1, vmax=1, center=0,
            annot_kws={'size': 11})
ax.set_title('Correlation Matrix — Numeric Features', fontweight='bold')

plt.tight_layout()
plt.savefig('fig5_correlation_heatmap.png', bbox_inches='tight')
plt.show()

# ── Fig 6: Missing Values Heatmap ─────────────────────────────────────────
fig, ax = plt.subplots(figsize=(10, 4))
missing_matrix = df[numeric_cols + ['showname', 'slug']].isnull()
sns.heatmap(missing_matrix.T, cmap='YlOrRd', cbar=True, ax=ax,
            xticklabels=False, linewidths=0)
ax.set_title('Missing Value Map (yellow = missing)', fontweight='bold')
ax.set_xlabel('Row index')

plt.tight_layout()
plt.savefig('fig6_missing_values.png', bbox_inches='tight')
plt.show()

# ── Fig 7: Avg Rating per Top Keyword ─────────────────────────────────────
kw_plot = kw_stats_df.sort_values('avg_rating', ascending=True)

fig, ax = plt.subplots(figsize=(10, 6))
bars = ax.barh(kw_plot['keyword'], kw_plot['avg_rating'],
               color=sns.color_palette('coolwarm', len(kw_plot)), edgecolor='white')
ax.axvline(df['rating'].mean(), color='black', linestyle='--', lw=1.2,
           label=f"Overall mean: {df['rating'].mean():.2f}")
for bar, val in zip(bars, kw_plot['avg_rating']):
    ax.text(bar.get_width() + 0.02, bar.get_y() + bar.get_height()/2,
            f'{val:.2f}', va='center', fontsize=9)
ax.set_title('Average Rating per Top 15 Keyword', fontweight='bold')
ax.set_xlabel('Average Rating')
ax.set_xlim(0, kw_plot['avg_rating'].max() + 0.5)
ax.legend()

plt.tight_layout()
plt.savefig('fig7_keyword_avg_rating.png', bbox_inches='tight')
plt.show()

# ── Fig 8: Token Count Distribution ───────────────────────────────────────
fig, ax = plt.subplots(figsize=(8, 5))
tc = df['token_count'].value_counts().sort_index()
ax.bar(tc.index, tc.values, color=sns.color_palette('pastel')[0], edgecolor='steelblue', lw=1.2)
for x, y in zip(tc.index, tc.values):
    ax.text(x, y + 0.5, str(y), ha='center', fontsize=10, color='dimgray')
ax.set_title('Distribution of Token Count per Show Name', fontweight='bold')
ax.set_xlabel('Token Count (words in show name)')
ax.set_ylabel('Number of Shows')
ax.xaxis.set_major_locator(mticker.MaxNLocator(integer=True))

plt.tight_layout()
plt.savefig('fig8_token_count_distribution.png', bbox_inches='tight')
plt.show()

fig, ax = plt.subplots(figsize=(10, 6))
sns.scatterplot(x='avg_episodes', y='avg_rating', data=kw_stats_df,
                hue='keyword', size='show_count', sizes=(50, 500),
                palette='viridis', legend='full', ax=ax)

ax.set_title('Average Rating vs. Average Episodes per Top Keyword',
             fontweight='bold')
ax.set_xlabel('Average Episodes')
ax.set_ylabel('Average Rating')
ax.grid(True, linestyle='--', alpha=0.7)

# Place legend outside the plot for better readability
plt.legend(bbox_to_anchor=(1.05, 1), loc='upper left', borderaxespad=0.)

plt.tight_layout()
plt.savefig('fig9_keyword_rating_episodes_scatter.png', bbox_inches='tight')
plt.show()

"""---
## 6. Summary Report
"""

print('=' * 55)
print('          SHOWS DATASET — SUMMARY REPORT')
print('=' * 55)
print(f"  Total shows          : {len(df):,}")
print(f"  Columns              : {df.shape[1]}")
print(f"  Shows missing seasons: {df['seasons'].isnull().sum()} ({df['seasons'].isnull().mean()*100:.1f}%)")
print()
print('  ── Ratings ──────────────────────────────────')
print(f"  Mean rating          : {df['rating'].mean():.2f}")
print(f"  Median rating        : {df['rating'].median():.2f}")
print(f"  Std dev              : {df['rating'].std():.2f}")
print(f"  Range                : {df['rating'].min():.1f} – {df['rating'].max():.1f}")
print()
print('  ── Episodes ─────────────────────────────────')
print(f"  Mean episodes        : {df['episodes'].mean():.1f}")
print(f"  Median episodes      : {df['episodes'].median():.0f}")
print(f"  Max episodes         : {df['episodes'].max()}")
print()
print('  ── Keywords ─────────────────────────────────')
print(f"  Unique keywords      : {len(freq):,}")
print(f"  Total occurrences    : {len(all_words):,}")
top3 = ', '.join([f"{w}({c})" for w, c in freq.most_common(3)])
print(f"  Top 3 keywords       : {top3}")
print()
print('  ── Highest-rated shows ──────────────────────')
top5 = df.nlargest(5, 'rating')[['showname','rating','episodes','seasons']]
print(top5.to_string(index=False))
print('=' * 55)