# -*- coding: utf-8 -*-
"""tv_shows_ir_pipeline.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DdIDmi0LKaNIsDS_3EOqmlVFtwD0bXRg

# 📺 TV Shows — Information Retrieval Preprocessing Pipeline

This notebook builds a complete IR text preprocessing pipeline for a scraped TV shows dataset.

**Dataset columns:** `link`, `showname`, `seasons`, `episodes`, `rating`, `poster`

**Text fields processed:**
- `showname` — primary text field (title of the show)
- `slug` — extracted from the URL (provides a secondary clean token source)

**Pipeline steps:** Lowercase → Remove punctuation/special chars → Remove numbers → Tokenize → Remove stopwords → Lemmatize

> **Why Lemmatization over Stemming?**  
> Lemmatization uses vocabulary and morphological analysis to return proper dictionary base forms (e.g., *running* → *run*), making tokens more readable and meaningful for IR tasks. Stemming is faster but often produces non-words (e.g., *running* → *runn*). For a titles-based dataset where readability and retrieval precision matter, lemmatization is preferred.

---
## Step 0 — Install & Import Libraries
"""

# Install required libraries (run once in Colab)
!pip install nltk pandas --quiet

import pandas as pd
import re
import nltk

# Download required NLTK resources
nltk.download('punkt',        quiet=True)  # tokenizer
nltk.download('punkt_tab',    quiet=True)  # tokenizer tables (newer NLTK)
nltk.download('stopwords',    quiet=True)  # English stopword list
nltk.download('wordnet',      quiet=True)  # WordNet lexical DB for lemmatizer
nltk.download('omw-1.4',      quiet=True)  # Open Multilingual Wordnet (WordNet dep)

from nltk.tokenize import word_tokenize
from nltk.corpus   import stopwords
from nltk.stem     import WordNetLemmatizer

print("✅ Libraries ready.")

"""---
## Step 1 — Load the Dataset
"""

# ── Load CSV ────────────────────────────────────────────────────────────────
# Upload 'shows.csv' via Colab's file panel, then run this cell.
# If running locally, adjust the path accordingly.
CSV_PATH = 'shows.csv'

df_original = pd.read_csv(CSV_PATH)

print(f"Dataset shape : {df_original.shape[0]} rows × {df_original.shape[1]} columns")
print(f"Columns       : {df_original.columns.tolist()}")
print()
df_original.head()

"""---
## Step 2 — Explore & Identify Text Fields
"""

# ── Data types & basic stats ────────────────────────────────────────────────
print("=== Data Types ===")
print(df_original.dtypes)
print()

print("=== Missing Values ===")
print(df_original.isnull().sum())
print()

print("=== Numeric Stats ===")
df_original[['seasons','episodes','rating']].describe()

# ── Inspect the text fields ─────────────────────────────────────────────────
# Primary text field  : showname  (title of the show)
# Secondary text field: slug extracted from 'link' column (URL path segment)
#   e.g. https://seriesgraph.com/show/64464-112263  →  slug = "112263"
#   e.g. https://seriesgraph.com/show/103992-a-teacher → slug = "a-teacher"

print("Sample shownames:")
print(df_original['showname'].head(10).tolist())
print()
print("Sample links:")
print(df_original['link'].head(5).tolist())

"""---
## Step 3 — Before-Preprocessing Sample
Saving a snapshot of raw text before any changes.
"""

# ── Show 8 raw rows for comparison later ────────────────────────────────────
SAMPLE_IDX = [0, 1, 2, 10, 20, 50, 100, 200]   # hand-picked diverse rows

before_df = df_original.loc[SAMPLE_IDX, ['showname', 'link']].copy()
before_df.index.name = 'row'

print("=== BEFORE Preprocessing ===")
before_df

"""---
## Step 4 — Build the Preprocessing Pipeline

Each sub-step is its own function so the pipeline is easy to audit or swap out.
"""

# ── Shared resources (instantiated once for performance) ─────────────────────
STOP_WORDS  = set(stopwords.words('english'))
LEMMATIZER  = WordNetLemmatizer()


# ────────────────────────────────────────────────────────────────────────────
# SUB-STEP A: Lowercase
# ────────────────────────────────────────────────────────────────────────────
def to_lowercase(text: str) -> str:
    """Convert all characters to lowercase for uniform comparison."""
    return text.lower()


# ────────────────────────────────────────────────────────────────────────────
# SUB-STEP B: Remove punctuation & special characters
# ────────────────────────────────────────────────────────────────────────────
def remove_punctuation(text: str) -> str:
    """
    Replace anything that is NOT a letter, digit, or whitespace with a space.
    This handles: !?.,;:'\"-()[]{}@#$%^&*+= etc.
    Using a space (not empty string) prevents token merging: 'Spider-Man' → 'Spider Man'.
    """
    return re.sub(r'[^a-z0-9\s]', ' ', text)


# ────────────────────────────────────────────────────────────────────────────
# SUB-STEP C: Remove numbers
# ────────────────────────────────────────────────────────────────────────────
def remove_numbers(text: str) -> str:
    """
    Remove standalone digit tokens.
    Rationale: year numbers (e.g. '11.22.63') or episode counts carry
    little semantic weight for IR matching on titles.
    NOTE: If numbers ARE meaningful for your use-case (e.g. '24', '9-1-1'),
    comment out this step or add those titles to an exception list.
    """
    return re.sub(r'\b\d+\b', ' ', text)


# ────────────────────────────────────────────────────────────────────────────
# SUB-STEP D: Normalize whitespace
# ────────────────────────────────────────────────────────────────────────────
def normalize_whitespace(text: str) -> str:
    """Collapse multiple spaces / newlines into a single space and strip edges."""
    return re.sub(r'\s+', ' ', text).strip()


# ────────────────────────────────────────────────────────────────────────────
# SUB-STEP E: Tokenize
# ────────────────────────────────────────────────────────────────────────────
def tokenize(text: str) -> list[str]:
    """
    Split text into individual word tokens using NLTK's word_tokenize.
    Returns a list of strings (tokens).
    """
    return word_tokenize(text)


# ────────────────────────────────────────────────────────────────────────────
# SUB-STEP F: Remove stopwords
# ────────────────────────────────────────────────────────────────────────────
def remove_stopwords(tokens: list[str]) -> list[str]:
    """
    Filter out common English words (the, a, is, in, …) that carry
    little discriminative power in IR tasks.
    Also drops single-character tokens as noise.
    """
    return [
        tok for tok in tokens
        if tok not in STOP_WORDS and len(tok) > 1
    ]


# ────────────────────────────────────────────────────────────────────────────
# SUB-STEP G: Lemmatize
# ────────────────────────────────────────────────────────────────────────────
def lemmatize(tokens: list[str]) -> list[str]:
    """
    Reduce each token to its dictionary base form (lemma) using WordNet.
    Examples: 'monsters' → 'monster', 'running' → 'run'

    Why lemmatization and NOT stemming?
    - Stemming (Porter/Snowball) strips suffixes aggressively, often producing
      non-words (e.g. 'bastard' → 'bastard', 'monsters' → 'monster' ✓ but
       'series' → 'seri' ✗).
    - Lemmatization uses WordNet's vocabulary, so output tokens are always
      valid English words — better for downstream retrieval and readability.
    """
    return [LEMMATIZER.lemmatize(tok) for tok in tokens]


print("✅ Preprocessing functions defined.")

# ── Master pipeline function ─────────────────────────────────────────────────
def preprocess_text(text) -> list[str]:
    """
    Full IR preprocessing pipeline for a single text string.
    Returns a list of clean lemmatized tokens.
    Handles None / NaN gracefully.
    """
    # Guard against missing values
    if not isinstance(text, str) or not text.strip():
        return []

    text = to_lowercase(text)          # A: lowercase
    text = remove_punctuation(text)    # B: remove punctuation
    text = remove_numbers(text)        # C: remove numbers
    text = normalize_whitespace(text)  # D: tidy whitespace
    tokens = tokenize(text)            # E: tokenize
    tokens = remove_stopwords(tokens)  # F: drop stopwords
    tokens = lemmatize(tokens)         # G: lemmatize
    return tokens


# ── Helper: extract URL slug ─────────────────────────────────────────────────
def extract_slug(url) -> str:
    """
    Pull the show-name segment from the URL path.
    e.g.  '.../show/103992-a-teacher'  →  'a teacher'
    The numeric ID prefix (e.g. '103992-') is stripped first.
    """
    if not isinstance(url, str):
        return ''
    slug = url.rstrip('/').split('/')[-1]   # last URL segment
    slug = re.sub(r'^\d+-', '', slug)        # drop leading numeric id
    return slug.replace('-', ' ')            # hyphens → spaces


print("✅ Pipeline assembled.")

"""---
## Step 5 — Apply Pipeline to the Dataset
"""

# ── Work on a copy — ORIGINAL DataFrame is never modified ────────────────────
df_processed = df_original.copy()

# ── Extract URL slug as a secondary text source ──────────────────────────────
df_processed['slug'] = df_processed['link'].apply(extract_slug)

# ── Apply preprocessing pipeline ────────────────────────────────────────────
df_processed['showname_tokens'] = df_processed['showname'].apply(preprocess_text)
df_processed['slug_tokens']     = df_processed['slug'].apply(preprocess_text)

# ── Combined token field (union of showname + slug tokens, deduplicated) ──────
# Useful as a single 'document' field for IR indexing
def merge_tokens(row):
    seen = set()
    merged = []
    for tok in row['showname_tokens'] + row['slug_tokens']:
        if tok not in seen:
            seen.add(tok)
            merged.append(tok)
    return merged

df_processed['all_tokens'] = df_processed.apply(merge_tokens, axis=1)

print(f"✅ Pipeline applied to {len(df_processed)} rows.")
print()
# Quick sanity check
print(df_processed[['showname', 'showname_tokens', 'all_tokens']].head(5).to_string())

"""---
## Step 6 — Before vs After Comparison
"""

# ── Side-by-side comparison for the sample rows ──────────────────────────────
print("=" * 70)
print("BEFORE vs AFTER PREPROCESSING")
print("=" * 70)

for idx in SAMPLE_IDX:
    row = df_processed.loc[idx]
    print(f"\nRow {idx}")
    print(f"  BEFORE  showname : {df_original.loc[idx, 'showname']}")
    print(f"  AFTER   tokens   : {row['showname_tokens']}")
    print(f"  SLUG extracted   : {row['slug']}")
    print(f"  SLUG tokens      : {row['slug_tokens']}")
    print(f"  ALL tokens       : {row['all_tokens']}")
    print("-" * 70)

"""---
## Step 7 — Handle Noisy / Inconsistent Titles
"""

# ── Flag rows where showname_tokens came out empty (all noise / stopwords) ───
empty_mask = df_processed['showname_tokens'].apply(len) == 0
empty_rows = df_processed[empty_mask][['showname', 'slug', 'showname_tokens']]

print(f"Rows with empty showname_tokens: {empty_mask.sum()}")
if not empty_rows.empty:
    print(empty_rows)
else:
    print("None — all titles produced at least one token. ✅")

print()

# ── Check for very short titles (≤ 1 char) that might be junk ────────────────
short_mask = df_original['showname'].str.strip().str.len() <= 1
print(f"Shownames with ≤ 1 character: {short_mask.sum()}")
if short_mask.any():
    print(df_original[short_mask][['showname']])

# ── Token statistics ─────────────────────────────────────────────────────────
df_processed['token_count'] = df_processed['showname_tokens'].apply(len)

print("Token count statistics (showname_tokens):")
print(df_processed['token_count'].describe())
print()

# Titles that reduced to a single token (may need review)
single_token = df_processed[df_processed['token_count'] == 1][['showname', 'showname_tokens']]
print(f"Titles that became a single token ({len(single_token)} total):")
print(single_token.head(15).to_string())

"""---
## Step 8 — Final Processed DataFrame Overview
"""

# ── Select columns to keep in the processed output ───────────────────────────
# Original columns are preserved; new columns added at the end
ORIGINAL_COLS   = ['link', 'showname', 'seasons', 'episodes', 'rating', 'poster']
PROCESSED_COLS  = ['slug', 'showname_tokens', 'slug_tokens', 'all_tokens', 'token_count']

df_final = df_processed[ORIGINAL_COLS + PROCESSED_COLS].copy()

print(f"Final DataFrame shape: {df_final.shape}")
print(f"Columns: {df_final.columns.tolist()}")
print()
df_final.head(10)

"""---
## Step 9 — Save Processed Dataset to CSV
"""

OUTPUT_PATH = 'shows_processed.csv'

# Token lists are serialized as JSON strings (safe to re-parse later with ast.literal_eval)
df_save = df_final.copy()
for col in ['showname_tokens', 'slug_tokens', 'all_tokens']:
    df_save[col] = df_save[col].apply(str)   # "['monster', 'real', ...]"

df_save.to_csv(OUTPUT_PATH, index=False)
print(f"✅ Saved → {OUTPUT_PATH}  ({len(df_save)} rows)")

# Download in Colab
try:
    from google.colab import files
    files.download(OUTPUT_PATH)
    print("📥 Download triggered.")
except ImportError:
    print("(Not running in Colab — file saved to current directory.)")

"""---
## Step 10 — Quick Vocabulary Insights (Bonus)
"""

from collections import Counter

# Flatten all tokens across all rows into one list
all_tokens_flat = [tok for tokens in df_processed['all_tokens'] for tok in tokens]

counter = Counter(all_tokens_flat)

print(f"Total tokens in corpus : {len(all_tokens_flat)}")
print(f"Unique vocabulary size : {len(counter)}")
print()
print("Top 30 most frequent tokens:")
for term, freq in counter.most_common(30):
    print(f"  {term:<20} {freq}")

"""---
## Summary

| Step | Action | Function |
|------|--------|----------|
| A | Lowercase | `to_lowercase()` |
| B | Remove punctuation & special chars | `remove_punctuation()` |
| C | Remove numbers | `remove_numbers()` |
| D | Normalize whitespace | `normalize_whitespace()` |
| E | Tokenize | `tokenize()` |
| F | Remove stopwords | `remove_stopwords()` |
| G | Lemmatize (WordNet) | `lemmatize()` |

**New columns added to the dataset:**
- `slug` — cleaned show name extracted from the URL
- `showname_tokens` — preprocessed tokens from the show title
- `slug_tokens` — preprocessed tokens from the URL slug
- `all_tokens` — deduplicated union of both token sets (use this for IR indexing)
- `token_count` — number of tokens per title (useful for filtering)

The original columns are **unchanged**.
"""